---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "4"

sudo: false
dist: trusty

addons:
  chrome: stable

addons:
    firefox: "latest"

cache:
  yarn: true
  directories:
    - $HOME/.npm

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_install:
  - yarn global add bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version
  - bower install

script:
  - node_modules/.bin/ember try:each
